name: Deploy to DeployGate

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Deploy to DeployGate
        run: |
          curl -F "file=@build/app/outputs/flutter-apk/app-release.aab" \
            -F "token=${{deploygate_xusr_cJL4URDqI9TwQCYeXJ45JmDIzQ3P6D_2yj8pZ}}" \
            -F "message=Automated deployment to DeployGate" \
            https://deploygate.com/api/users/WMKavinga/apps/com.hsenid.surveyapp/deploys
